name: Publish new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'warning'
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Update version"
        run: |
          sed -i "s/\(project(WARDuino VERSION \)[0-9]\+\.[0-9]\+\.[0-9]\+/\1$VERSION/" CMakeLists.txt
          sed -i "s/\(version=\)[0-9]\+\.[0-9]\+\.[0-9]\+/\1$VERSION/" library.properties
        env:
          VERSION: ${{ inputs.version }}

      - name: Create and push new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add CMakeLists.txt library.properties
          git commit -m "🔖 Bump version to ${{ inputs.version }}"
          git push origin release
