name: Publish new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'warning'
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Update version"
        run: |
          sed -i "s/\(project(WARDuino VERSION \)[0-9]\+\.[0-9]\+\.[0-9]\+/\1$VERSION/" CMakeLists.txt
          sed -i "s/\(version=\)[0-9]\+\.[0-9]\+\.[0-9]\+/\1$VERSION/" library.properties
        env:
          VERSION: ${{ inputs.version }}

      - uses: EndBug/add-and-commit@v9
        with:
          add: '["CMakeLists.txt", "library.properties"]'
          message: "🔖 Bump version to ${{ inputs.version }}"
          default_author: github_actions

